
# Chinese menus

[[docs]]
  name = "关于 MapRoot"
  weight = 1
  identifier = "about"
  url = "/zh/about/"

[[docs]]
  name = "入门"
  weight = 5
  identifier = "getting-started"
  url = "/zh/getting-started/"

[[docs]]
  name = "特色"
  weight = 15
  identifier = "feature"
  post = "break"
  url = "/zh/feature/"

# Core languages.zh.menus

[[docs]]
  name = "城市"
  weight = 20
  identifier = "city"
  url = "/zh/city/"

[[docs]]
  name = "实体"
  weight = 23
  identifier = "entity"
  url = "/zh/entity/"

[[docs]]
  name = "类目"
  weight = 25
  identifier = "category"
  url = "/zh/category/"

[[docs]]
  name = "网站"
  weight = 30
  identifier = "website"
  url = "/zh/website/"

[[docs]]
  name = "状态"
  weight = 35
  identifier = "status"
  url = "/status/"

# LOW LEVEL ITEMS
[[docs]]
  name = "故障排除"
  weight = 60
  identifier = "troubleshooting"
  url = "/zh/troubleshooting/"

[[docs]]
  name = "工具"
  weight = 70
  identifier = "tool"
  url = "/zh/tool/"

[[docs]]
  name = "贡献"
  weight = 100
  post = "break"
  identifier = "contribute"
  url = "/zh/contribute/"
